### ISSUE TITLE
Problems with publish: js error

### ISSUE THREAD

**Issue by phnx47** [tanaka-takayoshi/nuget-publish-to-github-packages-action#2]
Sometimes I have error:
```
(node:2916) UnhandledPromiseRejectionWarning: TypeError: (s || "").replace is not a function
    at escapeData (/home/runner/work/_actions/tanaka-takayoshi/nuget-publish-to-github-packages-action/v2.1/dist/index.js:1268:10)
    at Command.toString (/home/runner/work/_actions/tanaka-takayoshi/nuget-publish-to-github-packages-action/v2.1/dist/index.js:1262:35)
    at issueCommand (/home/runner/work/_actions/tanaka-takayoshi/nuget-publish-to-github-packages-action/v2.1/dist/index.js:1225:30)
    at Object.issue (/home/runner/work/_actions/tanaka-takayoshi/nuget-publish-to-github-packages-action/v2.1/dist/index.js:1229:5)
    at error (/home/runner/work/_actions/tanaka-takayoshi/nuget-publish-to-github-packages-action/v2.1/dist/index.js:512:15)
    at Object.setFailed (/home/runner/work/_actions/tanaka-takayoshi/nuget-publish-to-github-packages-action/v2.1/dist/index.js:486:5)
    at /home/runner/work/_actions/tanaka-takayoshi/nuget-publish-to-github-packages-action/v2.1/dist/index.js:288:8
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
https://github.com/PrometheusClientNet/Prometheus.Client.HealthChecks/runs/703897357#step:6:42

But some build is ok...

**Comment by wildlingdev** [comment]
unfortunately, im experiencing the same failure. any workaround?
